### ISSUE TITLE
Cop: stanza order

### ISSUE THREAD

**Issue by jawshooah** [caskroom/rubocop-cask#1]
Should add a cop that checks stanza order/grouping in casks. Autocorrect support is a must, since this will require a mass update to all or most casks.

Refs caskroom/homebrew-cask#16161

**Comment by vitorgalvao** [comment]
Will be at https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#stanza-order once https://github.com/caskroom/homebrew-cask/pull/16184/ is merged (soon, if there are no objections).

**Comment by jawshooah** [comment]
@vitorgalvao Implemented in #9. Feel free to take a look if you're so inclined.
