### ISSUE TITLE
Bug with setting comment for `license :unknown`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/rubocop-cask#16]
Found this bug a few days ago when fixing all casks in [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial). Casks [in this situation](https://github.com/caskroom/homebrew-unofficial/blob/729ac8417be2166d1df985e356ee84c320faa7e3/Casks/7zx.rb#L12), when processed with `brew cask style --fix`, entered an infinite loop of appending the correct comment.

[A user just found the issue as well](https://github.com/caskroom/homebrew-cask/pull/17925#issuecomment-177512553).

Personally, since we’ll remove `license` anyway, I don’t find it a big deal. Even so, would it be better to just delete the rule (since fixing it would serve no purpose, and leaving it can lead to this bug)?

**Comment by jawshooah** [comment]
Definitely a bug, but I agree that it would be better to just remove the rule altogether since we're deprecating `license`. Will do so in the next release.
