### ISSUE TITLE
Transfer ownership to caskroom

### ISSUE THREAD

**Issue by jawshooah** [caskroom/rubocop-cask#3]
@vitorgalvao, what do you think about transferring ownership of this repository to @caskroom? I would still be the primary maintainer, but help and feedback from @caskroom/maintainers would be more than welcome. It also just makes sense, given the narrow focus of the plugin.

**Comment by vitorgalvao** [comment]
Sure thing, whatever works best for you.

**Comment by jawshooah** [comment]
From the [documentation](https://help.github.com/articles/transferring-a-repository/) on transferring a repository:

> Users must have admin or owner rights within the receiving organization before they can transfer a repository that they individually own. If the user does not already have this level of access, a temporary admin team can be created with only the user. The user sending the repository is the only one who can perform the transfer.

> Just as when transferring a repository between two organizations, when a repository is transferred from a user to an organization, the Owners team is the only group with read/write access to the repository, but they can choose to add other teams for further access. See "[Permission Levels for an Organization](https://help.github.com/articles/permission-levels-for-an-organization)" for more information.

So I'll need temporary admin access within the @caskroom organization.

**Comment by vitorgalvao** [comment]
> So I'll need temporary admin access within the @caskroom organization.

Make it permanent. No reason you shouldn’t have it, anyway.

**Comment by jawshooah** [comment]
:tada:
