### ISSUE TITLE
Cop: check for comment when url and homepage hostnames differ

### ISSUE THREAD

**Issue by jawshooah** [caskroom/rubocop-cask#4]
When the `url` and `homepage` have different hostnames, we expect to see a comment like this:

```rb
# amazonaws.com is the official download host per the vendor homepage
```

**Comment by adityadalal924** [comment]
@jawshooah Any helpful links on creating Cops? Figured I'd ask before blindly searching StackOverflow and the like.

**Comment by jawshooah** [comment]
The rubydocs for [rubocop](http://www.rubydoc.info/gems/rubocop/Astrolabe/Node), [astrolabe](http://www.rubydoc.info/gems/astrolabe/Astrolabe/Node), [parser](http://www.rubydoc.info/gems/parser/Parser/Source/Map), and [ast](http://www.rubydoc.info/gems/ast/AST/Node) are all pretty helpful, but honestly the best thing is to just look through the code. Unfortunately RuboCop doesn't have much in the way of documentation for creating custom cops.

**Comment by jawshooah** [comment]
Done in #25 and #26.
