### ISSUE TITLE
x-moto is failing style

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/rubocop-cask#42]
```
$ brew cask style x-moto
== x-moto.rb ==
C:  5:  3: download.tuxfamily.org does not match xmoto.tuxfamily.org, a comment has to be added above the url stanza. For details, see https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment
```

These do match, and no warning should be output. Pinging @reitermarkus since you made the original work on the cop for this check.

Alternatively, I understand that the cop might be overzealous in this case but scaling back on that might be undesirable (since it would weaken the check for other casks). If that’s the case, we simply add the cask to this one and can be done with it.

**Comment by reitermarkus** [comment]
Seems to be a bug (or an exception?) in PublicSuffix:

```ruby
PublicSuffix.domain('download.tuxfamily.org')
=> "download.tuxfamily.org"
PublicSuffix.domain('download.example.org')
=> "example.org"
```

**Comment by reitermarkus** [comment]
According to https://github.com/publicsuffix/list/pull/186, `tuxfamily.org` is now a public suffix, so effectively this means `download.tuxfamily.org` and `xmoto.tuxfamily.org` are to be considered separate domains.

**Comment by vitorgalvao** [comment]
Thank you for the research on it. Will add the comment, then.
